# Generated by Django 4.2.4 on 2023-09-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_added_category_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-time_update', 'title']},
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
